### PR TITLE
Ability to show a neutral message

### PR DESCRIPTION
**Pull request by dalgard**
Becomes relevant when customizing the state of the form for more advanced user handling.

### CODE REVIEW

**Comment by splendido** [comment]
could you please add the the new files to the list into `package.js`?

**Comment by dalgard** [comment]
Woops.

**Comment by splendido** [comment]
Thanks! 

...and now who's going to add the `atMessage` template to all other frameworks? ;-)

**Comment by dalgard** [comment]
I might do it, but is it your impression that anyone is using the `AccountsTemplates.state.form` dict to set messages manually? Maybe it would be relevant if we (I) added a `messageType: "error"`/`messageType: "message"` option to  the `ensureSignedIn` route in the same go.

**Comment by splendido** [comment]
Yeah, breaking changes should be associated with a major varsion number bump ;-)

What if we think about set this up nicely for v2.0? 
...if we say there can be only one *text* shown at a time, we could also think to use the very same template to show messages, errors, and successes changing its appearance base on the *text* type.

Something like:

```javascript
UserAccounts.setFormStatus('err', 'User not found');
UserAccounts.setFormStatus('msg', 'Must be logged in!');
```

and then let people configure texts together with their *type*.

Thoughts?


Btw, `atMessage` should be added to every package now.
If you wish to also test the possibility to pass additional options to the `ensureSignedIn` plugin, you're more than welcome!

**Pull request merged**
